[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation 'com.google.code.gson:gson:2.11.0'
  implementation 'org.openjdk.nashorn:nashorn-core:15.4'
  implementation "com.github.aliasifk:HackLights:$hackLightsVersion"
  implementation "com.github.Hangman:TuningFork:$tuningForkVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
